server:
  hostname: "localhost"
  port: 8090

gate_client:
  login_path: "/login"
  scheme: "http"
  port: 3000

tls:
  min_version: "1.2"
  cert_file: "repository/resources/security/server.cert"
  key_file: "repository/resources/security/server.key"

database:
  config:
    type: "postgres"
    hostname: "localhost"
    port: 5432
    name: "thunder_config"
    username: "postgres"
    password: "postgres"
    sslmode: "disable"

  runtime:
    type: "postgres"
    hostname: "localhost"
    port: 5432
    name: "thunder_runtime"
    username: "postgres"
    password: "postgres"
    sslmode: "disable"

  user:
    type: "postgres"
    hostname: "localhost"
    port: 5432
    name: "thunder_user"
    username: "postgres"
    password: "postgres"
    sslmode: "disable"

crypto:
  encryption:
    key: "file://repository/resources/security/crypto.key"
  password_hashing:
    algorithm: "PBKDF2"
  keys:
    - id: "default-key"
      cert_file: "repository/resources/security/signing.cert"
      key_file: "repository/resources/security/signing.key"

jwt:
    preferred_key_id: "default-key"

cors:
  allowed_origins:
    - "https://localhost:3000"

passkey:
  allowed_origins:
    - "https://localhost:8090"

authn_provider:
  type: "mosip"
  mosip:
    otp_base_url: "https://api-internal.collab.mosip.net/idauthentication/v1/otp/S1NfjLsrh2ng8eJ73Z1x8L7ryBBmzi0H2d2jGgLQOiE0h2X7Sv/"
    kyc_auth_base_url: "https://api-internal.collab.mosip.net/idauthentication/v1/kyc-auth/delegated/S1NfjLsrh2ng8eJ73Z1x8L7ryBBmzi0H2d2jGgLQOiE0h2X7Sv/"
    kyc_exchange_base_url: "https://api-internal.collab.mosip.net/idauthentication/v1/kyc-exchange/delegated/S1NfjLsrh2ng8eJ73Z1x8L7ryBBmzi0H2d2jGgLQOiE0h2X7Sv/"
    partner_certificate_url: "https://api-internal.collab.mosip.net/mosip-certs/ida-partner.cer"
    p12_file_path: "C:\\Users\\sachin.rana06\\Downloads\\bec4ca0b_50c5_4ed5_b6f9_53e4609e08fa.pfx"
    p12_password: "localtest"
    individual_id_type: "UIN"
    otp_channels:
      - "phone"
      - "email"
    env: "Staging"
    domain_uri: ""
    locales:
      - "eng"
    kyc_exchange_resp_type: "JWT"
    ida_otp_id: "mosip.identity.otp"
    ida_otp_version: "1.0"
    ida_kyc_auth_id: "mosip.identity.kycauth"
    ida_kyc_auth_version: "1.0"
    ida_kyc_exchange_id: "mosip.identity.kycexchange"
    ida_kyc_exchange_version: "1.0"
  
consent:
  enabled: true
  base_url: "http://localhost:4000/api/v1"